### ISSUE TITLE
'python2_download_facescrub.py' crashes in between the download for actresses

### ISSUE THREAD

**Issue by dyno8426** [lightalchemist/FaceScrub#2]
Similar to my previous query, while downloading the FaceScrub dataset for the actresses' images as follows:

$ python python2_download_facescrub.py facescrub_actresses.txt actresses/ --crop_face --logfile=actresses.log --timeout=30

The python script terminates, while downloading some file related to "Jessica Biel", giving the following error:

... [rest of the terminal output] ...
Downloading http://www.scienceandsupermodels.com/http://www.scienceandsupermodels.com/pictures//2009/04/jessica-biel-001.jpg
Traceback (most recent call last):
  File "python2_download_facescrub.py", line 308, in <module>
    main()
  File "python2_download_facescrub.py", line 302, in main
    save_image(counter, response, args.datasetpath, name.replace(' ', '_'), image_id, face_id, bbox, save_face=args.crop_face)
  File "python2_download_facescrub.py", line 274, in save_image
    logger.error("Line {number}: {error}: {url}".format(number=counter, error=e, url=url.encode("utf-8", "ignore")))
NameError: global name 'url' is not defined

Can someone please help me resolve this?
Thanks in advance.

**Comment by lightalchemist** [comment]
Fixed bug due to variable `url` not defined in `save_image()`.
